"""Export everything a static host (Netlify, no backend) needs, from the same code the server uses.

Writes
  frontend/prerender/pages.json   {route: {title, description, html}}: readable page text for prerendering
  frontend/public/llms.txt        plain-text site summary
  frontend/public/static-api/     the API's GET responses as JSON (model, environments, experiments,
                                  safety, flex, psi), plus experiments.csv, and
      predictor.json              the trained gradient-boosting model as plain trees (+ precomputed
                                  related-report lookups and report abstracts) so /predict and the
                                  simulator run in the browser with the same model
      kb.json                     the Ask IGNITE-AI knowledge base passages + retrieval settings so
                                  questions are answered in the browser from the same NASA sources
The frontend uses these files when no backend is reachable (see frontend/src/lib/api.ts).

Run from backend/:  python -m scripts.export_static
(setup.bat runs it before the frontend build; re-run it after changing data or content.)
"""
from __future__ import annotations
import json, pathlib, sys

HERE = pathlib.Path(__file__).resolve()
BACKEND = HERE.parents[1]
sys.path.insert(0, str(BACKEND))

from app.main import _static_block  # noqa: E402  (same function the server uses)
from src.content import static_html  # noqa: E402
from src.compute.predict import artifacts  # noqa: E402

FRONTEND = BACKEND.parent / "frontend"
STATIC_API = FRONTEND / "public" / "static-api"


def build_pages() -> dict:
    pages = {}
    for route, label, title, desc in static_html.PAGES:
        pages[route] = {"label": label, "title": title, "description": desc, "html": _static_block(route)}
    pages["/404"] = {"label": "Not found", "title": "IGNITE-AI \u00b7 Page not found",
                     "description": "Page not found.", "html": _static_block("/404")}
    return pages


def build_llms() -> str:
    _, card, df = artifacts()
    return static_html.llms_txt(card, len(df), df["report_id"].nunique())


def build_predictor() -> dict:
    """The fitted sklearn pipeline as plain data: one-hot layout + every regression tree of the
    gradient-boosting ensemble. Prediction = softmax(init + learning_rate * sum of tree leaves)."""
    import pandas as pd
    from src.compute import retrieval
    from src.compute.model import FEATURES, NUMERIC, GRAVITY, CLASSES
    pipe, card, df = artifacts()
    pre, clf = pipe.named_steps["pre"], pipe.named_steps["clf"]
    ohe = pre.named_transformers_["cat"]
    x0 = pd.DataFrame([{c: df.iloc[0][c] for c in FEATURES}])
    init = clf._raw_predict_init(pre.transform(x0))[0]
    trees = []
    for stage in clf.estimators_:
        row = []
        for est in stage:
            t = est.tree_
            row.append({"f": t.feature.tolist(), "t": t.threshold.tolist(), "l": t.children_left.tolist(),
                        "r": t.children_right.tolist(), "v": t.value[:, 0, 0].tolist()})
        trees.append(row)
    # Related NTRS reports for a prediction depend only on these query words (retrieval.query_for),
    # so every combination is looked up here with the same TF-IDF index the server uses.
    materials = sorted(set(card["training_range"]["materials"]) | set(retrieval.MATERIAL_WORDS))
    reports, related = {}, {}
    for m in materials:
        for d in ("concurrent", "opposed", "quiescent"):
            for low_flow in (1, 0):
                for low_p in (1, 0):
                    for pred in (None, *CLASSES):
                        inp = {"material": m, "flow_direction": d, "flow_cm_s": 1.0 if low_flow else 20.0,
                               "pressure_kpa": 50.0 if low_p else 101.3}
                        hits = retrieval.search(retrieval.query_for(inp, pred), k=3)
                        for h in hits:
                            reports.setdefault(h["report_id"], {k: h[k] for k in ("title", "date", "source_url", "abstract_snippet")})
                        related[f"{m}|{d}|{low_flow}|{low_p}|{pred or ''}"] = [[h["report_id"], h["score"]] for h in hits]
    abstracts = {}
    for rid in sorted(set(df["report_id"].str.replace("NTRS ", "", regex=False))):
        doc = retrieval.get_abstract(rid)
        if doc:
            abstracts[rid] = {"title": doc["title"], "abstract": (doc.get("abstract") or "")[:600]}
    return {
        "note": "Generated by backend/scripts/export_static.py from data/artifacts/model.joblib. Do not edit.",
        "features": {"numeric": NUMERIC + [GRAVITY], "categorical": {c: [str(v) for v in cats] for c, cats in zip(ohe.feature_names_in_, ohe.categories_)}},
        "classes": [str(c) for c in clf.classes_], "learning_rate": float(clf.learning_rate),
        "init": [float(v) for v in init], "trees": trees,
        "related": related, "reports": reports, "abstracts": abstracts,
    }


def _span(text: str, part):
    """Store a passage's quote/data as [start, end] offsets into its text when possible (smaller file)."""
    if not part:
        return None
    i = text.find(part)
    return [i, i + len(part)] if i >= 0 else part


def build_kb() -> dict:
    from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
    from src.compute import kb, psi_data
    ps = kb.passages()
    compare = {}
    for inv in psi_data.investigations():
        rows = kb._compare([inv["accession"]], [])
        if rows:
            compare[inv["accession"]] = rows[0]
    return {
        "note": "Generated by backend/scripts/export_static.py from src/compute/kb.py. Do not edit.",
        "settings": {"min_score": kb.MIN_SCORE, "min_coverage": kb.MIN_COVERAGE, "token_pattern": r"(?u)\b[\w][\w\-]*\b",
                     "ngram_range": [1, 2], "sublinear_tf": True, "stop_words": sorted(ENGLISH_STOP_WORDS)},
        "acronyms": kb.ACRONYMS, "domain": sorted(kb.DOMAIN), "generic": sorted(kb.GENERIC), "expand": kb.EXPAND,
        "compare": compare,
        "passages": [[p["id"], p["kind"], p["title"], p["text"], p["url"], p["source"],
                      _span(p["text"], p["quote"]), _span(p["text"], p["data"])] for p in ps],
    }


def build_static_api() -> dict:
    """The API's GET responses, produced by the very same route functions."""
    from fastapi.encoders import jsonable_encoder
    from app import main as M
    out = {
        "model": M.model(),
        "environments": M.environments(),
        "experiments": M.experiments(None, None),
        "safety": M.safety(None),
        "flex": M.flex(False, False),
        "psi": M.psi(),
        "predictor": build_predictor(),
        "kb": build_kb(),
    }
    return {k: jsonable_encoder(v) for k, v in out.items()}


def write_static_api() -> None:
    STATIC_API.mkdir(parents=True, exist_ok=True)
    for name, obj in build_static_api().items():
        (STATIC_API / f"{name}.json").write_text(json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + "\n",
                                                 encoding="utf-8", newline="\n")
    csv = (BACKEND / "data" / "experiments.csv").read_bytes().replace(b"\r\n", b"\n")
    (STATIC_API / "experiments.csv").write_bytes(csv)


def main() -> None:
    out = FRONTEND / "prerender" / "pages.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(build_pages(), ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
    (FRONTEND / "public" / "llms.txt").write_text(build_llms(), encoding="utf-8", newline="\n")
    write_static_api()
    print(f"wrote {out.relative_to(BACKEND.parent)}, frontend/public/llms.txt and frontend/public/static-api/")


if __name__ == "__main__":
    main()
