// Post-build step: prerender every page for static hosting (Netlify).
//
// For each route in prerender/pages.json (exported from the backend by
// `python -m scripts.export_static`), write dist/<route>/index.html containing the
// page's own <title>, meta description and readable server-rendered text inside #root,
// so AI tools and crawlers that do not run JavaScript can read every page. React
// replaces that markup when it loads. Also writes dist/404.html, keeps the untouched
// app shell as dist/app-shell.html (used by the local FastAPI server), and generates
// dist/_redirects. If IGNITE_API_URL names a backend, /api/* etc. are proxied to it; if it is
// empty or unset (static-only hosting), no proxy is written and every page carries
// <meta name="ignite-api" content="off"> so the app computes predictions and answers in the
// browser from public/static-api/ without ever calling /api.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')
const pagesFile = join(root, 'prerender', 'pages.json')
const shellFile = join(dist, 'index.html')
if (!existsSync(shellFile)) throw new Error('dist/index.html missing: run vite build first')
if (!existsSync(pagesFile)) throw new Error('prerender/pages.json missing: run `python -m scripts.export_static` in backend/')

const shell = existsSync(join(dist, 'app-shell.html')) ? readFileSync(join(dist, 'app-shell.html'), 'utf8') : readFileSync(shellFile, 'utf8')
writeFileSync(join(dist, 'app-shell.html'), shell)
const pages = JSON.parse(readFileSync(pagesFile, 'utf8'))

// Absolute URLs for social previews: Netlify sets URL (the site's main address) at build time.
const siteUrl = (process.env.URL || process.env.SITE_URL || '').replace(/\/+$/, '')
// Backend URL: the ONE place it is set is IGNITE_API_URL in netlify.toml ([build.environment]).
const apiRaw = (process.env.IGNITE_API_URL || '').trim()
const api = /^(off|none|false|0)?$/i.test(apiRaw) ? '' : apiRaw.replace(/\/+$/, '')
const esc = s => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

function render(page) {
  let html = shell
  if (!/<div id="root">\s*<\/div>/.test(html)) throw new Error('app shell has no empty <div id="root"></div>')
  html = html.replace(/<div id="root">\s*<\/div>/, () => `<div id="root">${page.html}</div>`)
  html = html.replace(/<title>[\s\S]*?<\/title>/, () => `<title>${esc(page.title)}</title>`)
  html = html.replace(/<meta name="description" content="[^"]*"/, () => `<meta name="description" content="${esc(page.description)}"`)
  if (siteUrl) html = html.split('content="/og-image.png"').join(`content="${siteUrl}/og-image.png"`)
  if (!api) html = html.replace('</head>', '  <meta name="ignite-api" content="off">\n  </head>')
  return html
}

let n = 0
for (const [route, page] of Object.entries(pages)) {
  if (route === '/404') { writeFileSync(join(dist, '404.html'), render(page)); n++; continue }
  const file = route === '/' ? shellFile : join(dist, route.replace(/^\//, ''), 'index.html')
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, render(page))
  n++
}

const redirects = ['# Generated by frontend/scripts/prerender.mjs at build time. Edit IGNITE_API_URL in netlify.toml instead.']
if (api) redirects.push(
  `/api/*          ${api}/api/:splat   200`,
  `/health         ${api}/health       200`,
  `/docs           ${api}/docs         200`,
  `/openapi.json   ${api}/openapi.json 200`,
)
redirects.push('/demo           /simulator          301', '/demo/          /simulator          301', '')
writeFileSync(join(dist, '_redirects'), redirects.join('\n'))
console.log(`prerendered ${n} pages${siteUrl ? ` (site URL ${siteUrl})` : ''}; ` +
  (api ? `API proxied to ${api}` : 'static-only (no backend): predictions and answers run in the browser'))
